# -*- coding: utf-8 -*-
"""ใจความสำคัญ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYLlDbFQYdrBLOBKNyK8SmlLdF5yD9iy

# แยก
"""

# คำตอบนักเรียน (text)
student_answer = """สื่อสังคมหรือสื่อออนไลน์ เป็นสื่อหรือช่องทางการแพร่กระจายข่าวสารหรือข้อมูลต่างๆ เช่น การขายสินค้า นำเสนอข่าวสารที่เท็จจริง เป็นต้น สื่อสังคมออนไลน์มีทั้งดีและทั้งไม่ดี อย่างไรก็ตาม ควรใช้สื่อออนไลน์อย่างระมัดระวัง ไม่ควรเปิดเผยข้อมูลข้อมูลส่วนตัวออกไป เพราะ จะทำให้เป็นเราตกเป็นเหยื่อของมิจฉาชีพได้ เพราะฉะนั้น การใช้สื่อสังคมออนไลน์ เป็นสิ่งที่ความสำคัญ ควรเลือกในทางที่ถูกต้องดีกว่า"""

import re

# คีย์เวิร์ดเป้าหมาย
keypoints_1 = [
          # ข้อ 1: ต้องอยู่ใน 5 คำแรก
    ["เผยแพร่" ,"แพร่กระจาย", "ค้นหา"], # ข้อ 2: เจอคำใดคำหนึ่งก็ได้ ["เผยแพร่", "ค้นหา"]
    ["ข้อมูลข่าวสาร"]      # ข้อ 3: ต้องเจอคำนี้
]

# เงื่อนไขพิเศษ: ต้องมีในช่วงต้นข้อความ
must_have_in_first_5 = ["สื่อสังคม", "สื่อออนไลน์", "สื่อสังคมออนไลน์"]
must_have_in_first_10 = ["ช่องทาง", "เป็นสื่อ" , "เป็น"]

# ตรวจเฉพาะช่วงข้อความต้น ๆ (100-200 ตัวอักษร)
found_5 = any(kw in student_answer[:100] for kw in must_have_in_first_5)
found_10 = any(kw in student_answer[:200] for kw in must_have_in_first_10)
score_special = found_5 and found_10  # True / False

# ฟังก์ชันช่วยตัดคำแบบง่าย
def get_first_n_words(text, n):
    words = re.findall(r'\S+', text)
    return ' '.join(words[:n])

# ตรวจแต่ละข้อ
results = []
first_5_words = get_first_n_words(student_answer, 5)

# ข้อ 1: คำใน 5 คำแรก
found1 = any(kw in first_5_words for kw in keypoints_1[0])
results.append(("ข้อ 1", keypoints_1[0], found1))

# ข้อ 2 และ 3: ค้นหาทั้งข้อความ
for i, keywords in enumerate(keypoints_1[1:], start=2):
    found = any(kw in student_answer for kw in keywords)
    results.append((f"ข้อ {i}", keywords, found))

# นับจำนวนที่ผ่าน
pass_count = sum(1 for _, _, found in results if found)

# แสดงผลการตรวจทีละข้อ
for label, keywords, found in results:
    status = "✅ ผ่าน" if found else "❌ ไม่ผ่าน"
    print(f"{label}: คำที่ต้องมี {keywords} → {status}")

# แสดงผลรวมและผ่านหรือไม่
print(f"\nตรวจพบใจความสำคัญรวม: {pass_count} / 2 ข้อ")

if pass_count >= 1:
    print("➡️ สรุป: ✅ ผ่าน")
else:
    print("➡️ สรุป: ❌ ไม่ผ่าน")

# เงื่อนไขพิเศษ (แสดงเพิ่มเติม)
print("\n[เงื่อนไขพิเศษต้นประโยค]")
print(f" - พบคำใน 5 คำแรก: {'✅' if found_5 else '❌'}")
print(f" - พบ 'เป็นช่องทาง' ใน 10 คำแรก: {'✅' if found_10 else '❌'}")
print(f" - พบทั้ง 2 เงื่อนไข: {'✅ ผ่าน' if score_special else '❌ ไม่ผ่าน'}")

# ต้องเจอใน 5 คำแรก และ 10 คำแรกก็ได้ถือว่าได้คะแนน
# คำที่ต้องมี ต้องมี >= 1

# คีย์เวิร์ด
keypoints_1 = ["ไม่ระวัง", "ไม่ระมัดระวัง", "ขาดความรับผิดชอบ"]
keypoints_2 = ["โทษ", "ผลเสีย", "ข้อเสีย", "เกิดผลกระทบ", "สิ่งไม่ดี"]

# ตรวจเจอหรือไม่
found_1 = any(kw in student_answer for kw in keypoints_1)
found_2 = any(kw in student_answer for kw in keypoints_2)

# ตรวจเงื่อนไขพิเศษ: ถ้าพบข้อ 1 แล้วต้องพบข้อ 2 ด้วย
if found_1:
    if found_2:
        result = "✅ ผ่าน: มีทั้งคำเตือน (ไม่ระวัง) และผลกระทบ (โทษ/ข้อเสีย)"
    else:
        result = "❌ ไม่ผ่าน: กล่าวถึงไม่ระวัง แต่ไม่บอกผลกระทบ"
else:
    result = "❌ ไม่ผ่าน: ไม่พบคำที่แสดงความไม่ระมัดระวัง"

# แสดงผล
print("ตรวจคำที่เกี่ยวกับความไม่ระมัดระวังและผลกระทบ:")
print(f"- พบคำประเภท 'ไม่ระวัง' หรือใกล้เคียง: {'✅' if found_1 else '❌'}")
print(f"- พบคำประเภท 'โทษ/ผลเสีย/ข้อเสีย': {'✅' if found_2 else '❌'}")
print("➡️ สรุป:", result)

# ต้องมี 2 อัน

# คีย์เวิร์ดที่ต้องตรวจ (รายการเดียว)
keypoints_3 = [
    ["รู้เท่าทัน"] ,  ["รู้ทัน"]
]

# ตรวจสอบแต่ละข้อ
results = []
for i, keywords in enumerate(keypoints_3, start=1):
    found = any(kw in student_answer for kw in keywords)
    results.append((f"ข้อ {i}", keywords, found))

# แสดงผล
for item in results:
    label, keywords, found = item
    status = "✅ ผ่าน" if found else "❌ ไม่ผ่าน"
    print(f"{label}: คำที่ต้องมี {keywords} → {status}")

# 1 อันก็ได้

# คีย์เวิร์ดกลุ่มที่ 4
keypoints_4 = [
    ["การใช้สื่อ"] ,
    ["เจตนาแอบแฝง"],
    ["มีผลกระทบต่อ"] ,
    ["ความน่าเชื่อถือของข้อมูลข่าวสาร","ความน่าเชื่อถือของข่าวสาร"]
]

# ตรวจสอบแต่ละข้อ
results = []
for i, keywords in enumerate(keypoints_4, start=1):
    found = any(kw in student_answer for kw in keywords)
    results.append((f"ข้อ {i}", keywords, found))

# แสดงผล
for item in results:
    label, keywords, found = item
    status = "✅ ผ่าน" if found else "❌ ไม่ผ่าน"
    print(f"{label}: คำที่ต้องมี {keywords} → {status}")

# ต้อง 2 อันขึ้นไปยกเว้น 2,3

"""#ใจความ4ใหม่"""

# คีย์เวิร์ดกลุ่มที่ 4
keypoints_4 = [
    ["การใช้สื่อ"],
    ["เจตนาแอบแฝง"],
    ["มีผลกระทบต่อ"],
    ["ความน่าเชื่อถือของข้อมูลข่าวสาร", "ความน่าเชื่อถือของข่าวสาร"]
]

# ตรวจสอบแต่ละข้อ
results = []
for i, keywords in enumerate(keypoints_4, start=1):
    found = any(kw in student_answer for kw in keywords)
    results.append((f"ข้อ {i}", keywords, found))

# แสดงผลทีละข้อ
for label, keywords, found in results:
    status = "✅ ผ่าน" if found else "❌ ไม่ผ่าน"
    print(f"{label}: คำที่ต้องมี {keywords} → {status}")

# ตรวจสถานะแต่ละข้อ
found_1 = results[0][2]  # การใช้สื่อ
found_2 = results[1][2]  # เจตนาแอบแฝง
found_3 = results[2][2]  # มีผลกระทบต่อ
found_4 = results[3][2]  # ความน่าเชื่อถือ

# นับจำนวนที่ผ่าน
pass_count = sum([found_1, found_2, found_3, found_4])

# ตรวจเงื่อนไขพิเศษ: ถ้าผ่านแค่ข้อ 2 และ 3 เท่านั้น → ไม่ผ่าน
only_2_and_3 = (found_2 and found_3) and not (found_1 or found_4)

# สรุปผล
if pass_count >= 2 and not only_2_and_3:
    print(f"\nตรวจพบใจความสำคัญรวม: {pass_count} / 4 ข้อ")
    print("➡️ สรุป: ✅ ผ่าน (พบอย่างน้อย 2 ข้อ และไม่ใช่แค่ข้อ 2 กับ 3)")
else:
    print(f"\nตรวจพบใจความสำคัญรวม: {pass_count} / 4 ข้อ")
    print("➡️ สรุป: ❌ ไม่ผ่าน")

"""# รวม"""

!pip install pandas openpyxl

import pandas as pd
import re

# โหลดไฟล์ Excel
df = pd.read_csv("/content/sample_data/คำตอบนร 21 คน(Sheet1).csv")  # แก้ชื่อไฟล์ตามจริง

# --- ฟังก์ชันสำหรับตัดคำ ---
def get_first_n_words(text, n):
    words = re.findall(r'\S+', str(text))
    return ' '.join(words[:n])

# --- ตรวจกลุ่มที่ 1 ---
def score_group_1(text):
    keypoints_1 = [
        ["เผยแพร่", "แพร่กระจาย", "ค้นหา"],
        ["ข้อมูลข่าวสาร"]
    ]
    must_have_in_first_5 = ["สื่อสังคม", "สื่อออนไลน์", "สื่อสังคมออนไลน์"]
    must_have_in_first_10 = ["ช่องทาง", "เป็นสื่อ", "เป็น"]

    first_5_words = get_first_n_words(text, 5)
    found_1 = any(kw in first_5_words for kw in keypoints_1[0])
    found_2 = any(kw in text for kw in keypoints_1[1])
    found_5 = any(kw in text[:100] for kw in must_have_in_first_5)
    found_10 = any(kw in text[:200] for kw in must_have_in_first_10)

    score = 1 if (found_1 + found_2 >= 1 and found_5 and found_10) else 0
    return score

# --- ตรวจกลุ่มที่ 2 ---
def score_group_2(text):
    keypoints_1 = ["ไม่ระวัง", "ไม่ระมัดระวัง", "ขาดความรับผิดชอบ"]
    keypoints_2 = ["โทษ", "ผลเสีย", "ข้อเสีย", "เกิดผลกระทบ", "สิ่งไม่ดี"]
    found_1 = any(kw in text for kw in keypoints_1)
    found_2 = any(kw in text for kw in keypoints_2)
    return 1 if (found_1 and found_2) else 0

# --- ตรวจกลุ่มที่ 3 ---
def score_group_3(text):
    keypoints = ["รู้เท่าทัน", "รู้ทัน"]
    return 1 if any(kw in text for kw in keypoints) else 0

# --- ตรวจกลุ่มที่ 4 ---
def score_group_4(text):
    keypoints_4 = [
        ["การใช้สื่อ"],
        ["เจตนาแอบแฝง"],
        ["มีผลกระทบต่อ"],
        ["ความน่าเชื่อถือของข้อมูลข่าวสาร", "ความน่าเชื่อถือของข่าวสาร"]
    ]
    results = [any(kw in text for kw in group) for group in keypoints_4]
    found_indexes = [i for i, val in enumerate(results) if val]
    if set(found_indexes) == {1, 2}:
        return 0
    elif len(found_indexes) >= 2:
        return 1
    else:
        return 0

# --- ตรวจคะแนนแต่ละคำตอบ ---
df["score_1"] = df["student_answer_1"].apply(score_group_1)
df["score_2"] = df["student_answer_1"].apply(score_group_2)
df["score_3"] = df["student_answer_1"].apply(score_group_3)
df["score_4"] = df["student_answer_1"].apply(score_group_4)
df["total_score"] = df[["score_1", "score_2", "score_3", "score_4"]].sum(axis=1)

# --- บันทึกไฟล์ใหม่ ---
df.to_excel("ผลการให้คะแนน.xlsx", index=False)